repos:
  ### Run various small, general hooks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: destroyed-symlinks
      - id: check-vcs-permalinks
      - id: detect-private-key
      - id: check-yaml
      - id: end-of-file-fixer
      - id: mixed-line-ending

  # Run the ruff linter
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.6.8
    hooks:
    -   id: ruff
        types_or: [ python, pyi, jupyter ]
        args: [ --fix, --exit-non-zero-on-fix ]
    -   id: ruff-format
        types_or: [ python, pyi, jupyter ]

  - repo: https://github.com/RobertCraigie/pyright-python
    rev: v1.1.402
    hooks:
    - id: pyright
